import Head from "next/head";
import NavBar from "./navbar";
import { type ReactNode } from "react";
import { Toaster } from "react-hot-toast";

type Props = {
    children: ReactNode
}

const LandpageLayout = ({ children }: Props) => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Toaster position="top-right"/>
            <main className="container mx-auto flex min-h-screen flex-col">
                {children}
            </main>
        </>
    );
};

export default LandpageLayout;