import Head from "next/head";
import NavBar from "./navbar";
import { type ReactNode } from "react";

type Props = {
    children: ReactNode
}

const Layout = ({ children }: Props) => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar></NavBar>
            <main className="flex min-h-screen flex-col">
                {children}
            </main>
        </>
    );
};

export default Layout;